/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import org.cl.*;
import org.jfree.ui.RefineryUtilities;
import org.samsung.*;
import org.nike.*;
import org.nandini.*;
/**
 *
 * @author Win
 */
public class ManiUI extends javax.swing.JFrame {

    String userName = "";
    public ManiUI() {
        initComponents();
    }
    public ManiUI(String uname) {
        userName = uname;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tweet = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tweetActionPerformed(evt);
            }
        });

        jButton1.setText("Post");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Visuals");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tweet : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(tweet, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(tweet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
       
       String myTweet = tweet.getText();
       String response = "";
       if(myTweet.contains("samsung")){
           Samsung_Service service = new Samsung_Service();
           Samsung port = service.getSamsungPort();
           response = port.hello(userName+":"+myTweet);
           
           Spcloud_Service serviceSp = new Spcloud_Service();
       Spcloud portSp = serviceSp.getSpcloudPort();
        response = portSp.hello(userName+": "+myTweet);
       }
       else if(myTweet.contains("nike")){
           Nike_Service service = new Nike_Service();
           Nike port = service.getNikePort();
           response = port.hello(userName+":"+myTweet);
           
           Spcloud_Service serviceSp = new Spcloud_Service();
       Spcloud portSp = serviceSp.getSpcloudPort();
        response = portSp.hello(userName+": "+myTweet);
       }
       else if(myTweet.contains("nandini")){
           Nandini_Service service = new Nandini_Service();
           Nandini port = service.getNandiniPort();
           response = port.hello(userName+":"+myTweet);
           
           Spcloud_Service serviceSp = new Spcloud_Service();
       Spcloud portSp = serviceSp.getSpcloudPort();
        response = portSp.hello(userName+": "+myTweet);
       }
       else{
//       Spcloud_Service service = new Spcloud_Service();
//       Spcloud port = service.getSpcloudPort();
//        response = port.hello(userName+": "+myTweet);
       }
       
       JOptionPane.showMessageDialog(null,"Tweet updated!");
       }catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tweetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
       FileInputStream fisSam = new FileInputStream("C:\\myfinal project\\datacenter\\samfreq.txt");
       byte bbSam[] = new byte[fisSam.available()];
       fisSam.read(bbSam);
       fisSam.close();
       
       FileInputStream fisNik = new FileInputStream("C:\\myfinal project\\datacenter\\nikfreq.txt");
       byte bbNik[] = new byte[fisNik.available()];
       fisNik.read(bbNik);
       fisNik.close();
       
       FileInputStream fisNan = new FileInputStream("C:\\myfinal project\\datacenter\\nanfreq.txt");
       byte bbNan[] = new byte[fisNan.available()];
       fisNan.read(bbNan);
       fisNan.close();
       
       
       ArrayList<Float> allBlueFrequencies = new ArrayList<Float>();
       ArrayList<Float> allRedFrequencies = new ArrayList<Float>();
       ArrayList<String> allBrands = new ArrayList<String>();
       
       allBlueFrequencies.clear();
       allRedFrequencies.clear();
       allBrands.clear();
       
       allBrands.add("Samsung");
       allBrands.add("Nike");
       allBrands.add("Nandini");
       
       
       
       String allSams = new String(bbSam);
       StringTokenizer stSam = new StringTokenizer(allSams,":");
       while(stSam.hasMoreTokens()){
           allBlueFrequencies.add(Float.parseFloat(stSam.nextToken()));
           allRedFrequencies.add(Float.parseFloat(stSam.nextToken()));
       }
       
       String allNiks = new String(bbNik);
       StringTokenizer stNik = new StringTokenizer(allNiks,":");
       while(stNik.hasMoreTokens()){
           allBlueFrequencies.add(Float.parseFloat(stNik.nextToken()));
           allRedFrequencies.add(Float.parseFloat(stNik.nextToken()));
       }
       
       String allNans = new String(bbNan);
       StringTokenizer stNan = new StringTokenizer(allNans,":");
       while(stNan.hasMoreTokens()){
           allBlueFrequencies.add(Float.parseFloat(stNan.nextToken()));
           allRedFrequencies.add(Float.parseFloat(stNan.nextToken()));
       }
       
       final Barchar1 demo = new Barchar1("=====Overall Positivity in Websites=====",allBlueFrequencies,allBrands);
        demo.pack();
        RefineryUtilities.centerFrameOnScreen(demo);
        demo.setVisible(true);
        
        final Barchar1 demo1 = new Barchar1("=====Overall Negativity in Websites=====",allRedFrequencies,allBrands);
        demo1.pack();
        RefineryUtilities.centerFrameOnScreen(demo1);
        demo1.setVisible(true);

       
       }catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManiUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tweet;
    // End of variables declaration//GEN-END:variables
}
